import { AbstractDiagramDisplay } from './AbstractDiagramDisplay.js';
export { DEFAULT_SPHERE_COLOR as DEFAULT_NODE_COLOR } from './AbstractDiagramDisplay.js';
export { CayleyDiagramViewModel, CayleyDiagramView, createStaticCayleyDiagramView, createInteractiveCayleyDiagramView, createCayleyDiagramThumbnailView };
declare class CayleyDiagramViewModel {
    #private;
    get group(): any;
    get view(): any;
    get model(): any;
    setModel(model: any): void;
    setView(view: any): void;
    updateModel(field: any, value: any): void;
    update(field: any, value: any): void;
    setSize(x: any, y: any): void;
    resize(): void;
    showGraphic(): void;
    unitSquarePositions(): any;
    getImage(): any;
    get canvas(): any;
    toJSON(): any;
    fromJSON(jsonObject: any): void;
    draw(group: any, diagramNameOrStrategies: any, arrowGenerators: any): void;
}
declare class CayleyDiagramView extends AbstractDiagramDisplay {
    viewModel: any;
    display_labels: any;
    _label_scale_factor: any;
    _arrowhead_placement: any;
    _group: any;
    generator: any;
    _right_multiply: any;
    color_highlights: never[];
    ring_highlights: never[];
    square_highlights: never[];
    constructor(options?: {});
    getObjectsAtPoint(x: any, y: any): any;
    drawFromModel({ position, up }: {
        position: any;
        up: any;
    }, nodes: any, arrows: any): void;
    deleteAllObjects(): void;
    get sphere_scale_factor(): any;
    set sphere_scale_factor(new_scale_factor: any);
    createSpheres(sphere_data: any): void;
    moveSphere(sphere: any, position: any, moveContainingChunk?: boolean): void;
    unitSquarePosition(element: any): {
        x: number;
        y: number;
    };
    unitSquarePositions(): any;
    deleteAllSpheres(): void;
    drawAllHighlights(): void;
    drawHighlight(sphere: any, shape: any, highlight_color: any): void;
    updateHighlightRadius(): void;
    clearHighlightDefinitions(): void;
    deleteAllHighlights(): void;
    get label_scale_factor(): any;
    set label_scale_factor(label_scale_factor: any);
    createLabels(): void;
    updateLabelRadius(old_sphere_radius: any, new_sphere_radius: any): void;
    deleteAllLabels(): void;
    get arrowhead_placement(): any;
    set arrowhead_placement(arrowhead_placement: any);
    createLines(line_data: any): void;
    colorAllLines(): void;
    createStraightLine(line_datum: any): void;
    createCurvedLine(line_datum: any): void;
    createArrowhead(line_datum: any, curve: any, curve_length: any): any;
    offsetAroundSpheres(line_datum: any): number | undefined;
    redrawAllLines(): void;
    redrawLines(lines: any): void;
    deleteLines(lines: any): void;
    get chunks(): any;
    createChunks(chunk_data: any): void;
    deleteAllChunks(): void;
    moveChunkTo(chunk: any, position: any): void;
    get arrows(): any;
    get group(): any;
    set group(group: any);
    get nodes(): any;
    addArrows(newArrows: any): void;
    reColorArrows(): void;
    removeArrows(generators: any): void;
}
declare function createCayleyDiagramThumbnailView(options?: {}): CayleyDiagramViewModel;
declare function createStaticCayleyDiagramView(model: any, options?: {}): CayleyDiagramViewModel;
declare function createInteractiveCayleyDiagramView(model: any, options?: {}): CayleyDiagramViewModel;
