/*

# Gesture interpreter

Effort to treat event sequences in a device-independent manner.  Interpretations include:
 * click / tap -- [Select](#select)
 * right click (context menu) / long tap -- [Context menu](#context-menu)
 * drag-and-drop / one-finger drag -- [Drag-and-drop](#drag-and-drop)
 * wheel -- [Zoom](#zoom)
 * two-finger pinch -- [Pinch](#pinch)
```javascript
 */
import * as GEUtils from './GEUtils.js'
import * as THREE from '../lib/externals.js'

const CLICK_TIME = 500  // max time for a short click (ms)
const CLICK_MOVE = 10   // max move for a click (px)

type resetFunction = () => void
const registeredResets: resetFunction[] = []

function register (reset: resetFunction) {
   registeredResets.push(reset)
}

function claim (myReset: resetFunction) {
   registeredResets.forEach((reset) => {
      if (reset !== myReset) {
         reset()
      }
   })
}

function resetAll () {
   registeredResets.forEach((reset) => reset())
}
/*
```
### Select

Executes callback on click:
 * pointerdown followed by pointerup
 * primary pointer only (no two-finger gestures)
 * left click (button == 0) on mouse device
 * satisfies [isClick](#utility-routines) for time, motion
 * resulting click event not blocked

callback(event) called with last pointer event
```javascript
 */
export type SelectCallback = (event: PointerEvent | MouseEvent) => void;

export function recognizeSelect (element: HTMLElement, callback: SelectCallback) {
   let startEvent: Maybe<PointerEvent> = null

   const reset = () => { startEvent = null }
   register(reset)

   element.addEventListener('pointerdown',
      (event: PointerEvent) => {
         startEvent = (event.isPrimary && event.button === 0) ? event : null
      })

   element.addEventListener('click',
      (event: MouseEvent) => {
         if (startEvent != null && isClick(startEvent, event)) {
            claim(reset)
            callback(event)
         }
         startEvent = null
      })
}
/*
```
### Context menu

Executes callback following right click or long tap:
 * pointerdown followed by a period of time with no (non-trivial) movement
 * primary pointer only (no two-finger gestures)
 * right click (button == 2) on mouse device
 * can be triggered by pointerup event
 * can be triggered by timer on `options.returnOnLongTapTimeout` (options default)
 * satisfies [isLongTap](#utility-routines) for time, motion
 * resulting click event not blocked

callback(event) called with last pointer event
```javascript
 */
export type ContextMenuCallback = (event: PointerEvent) => void;
export type ContextMenuOptions = {
   returnOnLongTapTimeout?: boolean
}

export function recognizeContextMenu (
   element: HTMLElement,
   callback: ContextMenuCallback,
   options: ContextMenuOptions = {returnOnLongTapTimeout: true}
) {
   let startEvent: Maybe<PointerEvent> = null
   let lastEvent: Maybe<PointerEvent> = null
   let longTapTimerId: Maybe<TimeoutID> = null

   function reset () {
      startEvent = null
      lastEvent = null
      if (longTapTimerId != null) {
         window.clearTimeout(longTapTimerId)
         longTapTimerId = null
      }
      element.removeEventListener('pointermove', moveHandler)
   }
   register(reset)

   function moveHandler (event: PointerEvent) {
      lastEvent = event
   }

   function longTapTimer () {
      if (  startEvent != null
         && lastEvent != null
         && longTapTimerId != null
         && isTrivialMove(startEvent, lastEvent)
      ) {
         claim(reset)
         callback(lastEvent)
      }
      reset()
   }

   element.addEventListener('pointerdown',
      (event: PointerEvent) => {
         if (event.isPrimary && (event.pointerType != 'mouse' || event.button === 2)) {
            startEvent = event
            lastEvent = event
            element.addEventListener('pointermove', moveHandler)
            if (options.returnOnLongTapTimeout) {
               longTapTimerId = window.setTimeout(longTapTimer, CLICK_TIME)
            }
         }
      })

   element.addEventListener('pointerup',
      (event: PointerEvent) => {
         if (  startEvent != null
            && event.isPrimary
            && (  (event.pointerType === 'mouse' && event.button === 2)
               || isLongTap(startEvent, event) )
         ) {
            claim(reset)
            callback(event)
         }
         reset()
      })
}
/*
```
### Drag and Drop

Execute callback following (single-finger) drag-and-drop sequence:
 * ponterdown followed by any number of pointermove events and a possible terminating pointerup event
 * triggered by most recent pointermove or pointerup event
 * click generated by pointerup is received during capture phase and prevented from reaching other handlers

callback(startEvent, previousEvent, currentEvent, isDrop):
 * startEvent -- the initial pointerdown event
 * previousEvent -- the pointerdown or pointermove event immediately preceeding the current event
 * currentEvent -- the pointermove or pointerup event that triggered this callback
 * isDrop -- true if final event is pointerup
```javascript
 */
export type DragAndDropCallback =
   (startEvent: PointerEvent, previousEvent: PointerEvent, currentEvent: PointerEvent, isDrop: boolean) => void;
export type DragAndDropOptions = {
   returnOnLongTapTimeout?: boolean,
   rightClick?: boolean
};

const DEFAULT_RECOGNIZE_DRAG_AND_DROP_OPTIONS: DragAndDropOptions = {
   returnOnLongTapTimeout: false,
   rightClick: false
}

export function recognizeDragAndDrop (
   element: HTMLElement,
   callback: DragAndDropCallback,
   passedOptions: DragAndDropOptions = {}
) {
   const options = {...DEFAULT_RECOGNIZE_DRAG_AND_DROP_OPTIONS, ...passedOptions}

   let startEvent: Maybe<PointerEvent>    = null  // pointerdown event that initiates possible drag-and-drop sequence
   let previousEvent: Maybe<PointerEvent> = null  // pointerdown or last pointermove event
   let moveContext: Maybe<HTMLElement>    = null  // immediate containing .modal element, or document body
   let longTapTimerId: Maybe<TimeoutID>   = null  // id to cancel longTapTimer

   function reset () {
      startEvent = null
      previousEvent = null
      if (moveContext != null) {
         moveContext.removeEventListener('pointermove', moveHandler)
         moveContext = null
      }
      if (longTapTimerId != null) {
         clearTimeout(longTapTimerId)
         longTapTimerId = null
      }
   }
   register(reset)

   function moveHandler (event: PointerEvent) {
      if (  startEvent != null
         && event.isPrimary
         && event.buttons === (options.rightClick ? 2 : 1)  // default left mouse button
      ) {
         if (previousEvent != startEvent || !isClick(startEvent, event)) {  // is this really a move?
            claim(reset)
            callback(startEvent, previousEvent as PointerEvent, event, false)
            previousEvent = event
            if (longTapTimerId != null) {
               clearTimeout(longTapTimerId)
               longTapTimerId = null
            }
         }
      } else {
         reset()
      }
   }

   // invokes callback on long tap
   // (enables client to create drag image, for example)
   function longTapTimer () {
      if (startEvent != null) {
         claim(reset)
         callback(startEvent, previousEvent as PointerEvent, startEvent, false)
      }
      longTapTimerId = null
   }

   function clickStopper (event: MouseEvent) {
      event.stopPropagation()
   }

   element.addEventListener('pointerdown',
      (event: PointerEvent) => {
         if (  startEvent == null
            && event.isPrimary
            && event.button == (options.rightClick ? 2 : 0)  // default left mouse button
            && !element.contains((event.target as HTMLElement).closest('input'))
            && !element.contains((event.target as HTMLElement).closest('textarea'))
         ) {
            startEvent = event
            previousEvent = event
            moveContext = element.closest('.modal') || document.body
            moveContext.addEventListener('pointermove', moveHandler)
            if (options.returnOnLongTapTimeout) {
               longTapTimerId = window.setTimeout(longTapTimer, CLICK_TIME)
            }
         } else {
            reset()
         }
      })

   element.addEventListener('pointerup',
      (event: PointerEvent) => {
         if (startEvent != null && startEvent != previousEvent) {  // a move is being processed
            // the pointerup event that ends the drag also causes a click
            // below is a workaround to prevent the click from propagating:
            //    1) add an event listener that grabs the click during the capture phase,
            //       before bubbling phase listeners have a chance
            //    2) launch a timeout function to remove the capture phase listener after a second,
            //       in case the click is not generated for some reason
            element.addEventListener('click', clickStopper, { capture: true, once: true })
            window.setTimeout(
               () => element.removeEventListener('click', clickStopper, { capture: true }),
               1000
            )

            if (event.isPrimary && event.button === 0) {
               claim(reset)
               callback(startEvent, previousEvent as PointerEvent, event, true)
            }
         }
         reset()
      })
}
/*
```
#### PinchHandler

Execute callback(start, previous, current, isFinal) on pinch / spread touch gesture

```javascript
 */
export type PinchCallback =
   (startEvent: TouchEvent, previousEvent: TouchEvent, currentEvent: TouchEvent, isFinal: boolean) => void;

function recognizePinch (element: HTMLElement, callback: PinchCallback) {
   let startEvent: Maybe<TouchEvent> = null
   let previousEvent: Maybe<TouchEvent> = null

   function reset () {
      startEvent = null
      previousEvent = null
      element.removeEventListener('touchmove', touchMoveHandler)
   }
   register(reset)

   function touchMoveHandler (event: TouchEvent) {
      if (event.touches.length == 2) {
         claim(reset)
         callback(startEvent as TouchEvent, previousEvent as TouchEvent, event, false)
         previousEvent = event
      } else {
         reset()
      }
   }

   element.addEventListener('touchstart',
      (event: TouchEvent) => {
         if (event.touches.length == 2) {
            startEvent = event
            previousEvent = event
            element.addEventListener('touchmove', touchMoveHandler)
         } else {
            reset()
         }
      })

   element.addEventListener('touchend',
      (event: TouchEvent) => {
         if (startEvent != null) {
            claim(reset)
            callback(startEvent, previousEvent as TouchEvent, event, true)
         }
         reset()
      })
}
/*
```
#### WheelHandler

Execute callback(event) on wheel event

```javascript
 */

export type WheelCallback = (event: WheelEvent) => void;

function recognizeWheel (element: HTMLElement, callback: WheelCallback) {
   element.addEventListener('wheel', (event: WheelEvent) => {
      resetAll()
      callback(event)
   })
}
/*
```
### Zoom

Merged Zoom gesture, with Pinch and Wheel implementations

callback(scaleFactor, isFinal)

```javascript
 */

export type ZoomCallback = (scaleFactor: number, isFinal: boolean) => void;

export function recognizeZoom (element: HTMLElement,  zoomCallback: ZoomCallback) {
   // context in which we detect drag, scroll, etc. -- generally a .modal containing the element
   const contextElement: HTMLElement = element.closest('.modal') || document.body

   if (GEUtils.isTouchDevice()) {
      recognizePinch(contextElement, (_startEvent, previousEvent, currentEvent, isFinal) =>
         pinchZoomCallback(zoomCallback, previousEvent, currentEvent, isFinal)
      )
   } else {
      recognizeWheel(contextElement, (wheelEvent) => wheelZoomCallback(zoomCallback, wheelEvent))
   }
}

function pinchZoomCallback (
   zoomCallback: ZoomCallback,
   previousEvent: TouchEvent,
   currentEvent: TouchEvent,
   isFinal: boolean
) {
   const previousTouches = Array.from(previousEvent.touches)
   const currentTouches =
      (currentEvent.touches.length === 2)
         ? [currentEvent.touches[0], currentEvent.touches[1]]
         : (currentEvent.touches.length === 1)
            ? [currentEvent.touches[0], currentEvent.changedTouches[0]]
            : [currentEvent.changedTouches[0], currentEvent.changedTouches[1]]

   // ensure consistent ordering in touch vectors
   previousTouches.sort((a: Touch, b: Touch) => a.identifier - b.identifier)
   currentTouches.sort((a: Touch, b: Touch) => a.identifier - b.identifier)

   function spread (touchArray: Touch[]): number {
      return Math.hypot(touchArray[0].clientX - touchArray[1].clientX, touchArray[0].clientY - touchArray[1].clientY)
   }
   const rawScaling = spread(currentTouches) / spread(previousTouches) - 1

   zoomCallback(rawScaling, isFinal)
}

function wheelZoomCallback (zoomCallback: ZoomCallback, wheelEvent: WheelEvent) {
   if ((wheelEvent.target as HTMLElement).closest('.scrollable') != null) {
      return
   }

   const ZOOM_FACTOR = 0.05  // shrink/expand element by 5% per wheel click
   const rawScaling = Math.sign(wheelEvent.deltaY) * ZOOM_FACTOR
   zoomCallback(rawScaling, true)
}
/*
```
### Move and Resize

Swiss army knife routine to combine move and resize gestures on mouse, touchpad, and touch platforms.

Invokes callback(deltaX, deltaY, deltaWidth, deltaHeight, isDrop) on recognizing:
 * A drag initiated over an element with class [resize-handle](./ge3.css.md) causes a call to
     `callback(0, 0, dx, dy)` to resize the element keeping the top right corner in place.
 * A drag initiated over any other part of the element causes a call to
     `callback(dx, dy, 0, 0)` to move the element.
 * On a touch platform, a drag initiated outside the element causes a call to
     `callback(l*dx, t*dy, w*dx, h*dy)` to resize the element keeping the opposite side (corner)
     from the initial touch in place.
     The weights are chosen from {-1, 0, 1} according to the initial touch location.
 * A wheel or pinch event anywhere on the screen causes a call to
     `callback(-dw/2, -dh/2, dw, dh)` to resize the element keeping the center in place.
 * To give precedence to the browser's default scrolling action,
     * No action is taken on a wheel event over a `.scrollable` element.
     * No action is taken on a touch platform for a drag event initiated over a `.scrollable` element.
 * No resizing action is taken if the element is styled `resize=none`.

```javascript
 */

export type MoveResizeCallback =
   (
      deltaX: number,
      deltaY: number,
      deltaWidth: number,
      deltaHeight: number,
      isDrop?: boolean,
      movingElement?: Element
   ) => void;

export type ResizeCoefficient = {
   l: number,
   t: number,
   w: number,
   h: number
};

const resizeCoefficients: ResizeCoefficient[] = [
   { l: 1, t: 1, w: -1, h: -1 }, // quadrant 0
   { l: 0, t: 1, w: 0, h: -1 }, // 1
   { l: 0, t: 1, w: 1, h: -1 }, // 2
   { l: 1, t: 0, w: -1, h: 0 }, // 3
   { l: 1, t: 1, w: 0, h: 0 }, // 4
   { l: 0, t: 0, w: 1, h: 0 }, // 5
   { l: 1, t: 0, w: -1, h: 1 }, // 6
   { l: 0, t: 0, w: 0, h: 1 }, // 7
   { l: 0, t: 0, w: 1, h: 1 } // 8
]

export function recognizeMoveResize (element: HTMLElement, callback: MoveResizeCallback) {
   // context in which to register drag -- generally a .modal containing the element
   const contextElement: HTMLElement = element.closest('.modal') || document.body

   // save min width/height styling
   const elementStyle = getComputedStyle(element)
   const minElement = new THREE.Vector2(
      elementStyle.minWidth?.endsWith('px') ? parseFloat(elementStyle.minWidth) : 0,
      elementStyle.minHeight?.endsWith('px') ? parseFloat(elementStyle.minHeight) : 0
   )

   if (element.style.resize != 'none') {
      recognizeZoom(contextElement,
         (scale: number) => {
            const clientRect = element.getBoundingClientRect()
            const minimumDimension = Math.min(clientRect.width, clientRect.height)
            const minElementSize = Math.min(minElement.width, minElement.height)
            const scaleSign = Math.sign(scale)
            const scaleFactor = scaleSign * Math.min(1 + scaleSign * minElementSize / minimumDimension, Math.abs(scale))
            const sizeChange = new THREE.Vector2(clientRect.width, clientRect.height).multiplyScalar(scaleFactor)
            const limitedSizeChange = limitSizeChange(sizeChange)

            callback(-limitedSizeChange.x / 2, -limitedSizeChange.y / 2, limitedSizeChange.x, limitedSizeChange.y)
         })
   }

   if (GEUtils.isTouchDevice()) {
      recognizeDragAndDrop(contextElement,
         (  startEvent: PointerEvent,
            previousEvent: PointerEvent,
            currentEvent: PointerEvent,
            isDrop: boolean
         ) => {
            touchMove(startEvent, previousEvent, currentEvent, isDrop)
         })

      // Coefficients for startTouch, determined on first callback
      let startCoefficient: ResizeCoefficient

      function touchMove (
         startEvent: PointerEvent,
         previousEvent: PointerEvent,
         currentEvent: PointerEvent,
         isDrop: boolean
      ) {
         // Determine screen quadrant startEvent occured in (element is [4]):
         //   0  1  2
         //   3 [4] 5
         //   6  7  8
         if (startEvent == previousEvent) {
            const clientRect = element.getBoundingClientRect()
            const row = startEvent.clientY < clientRect.top ? 0 : (startEvent.clientY > clientRect.bottom ? 2 : 1)
            const col = startEvent.clientX < clientRect.left ? 0 : (startEvent.clientX > clientRect.right ? 2 : 1)
            const quadrant = 3 * row + col
            startCoefficient = resizeCoefficients[quadrant]

            // Don't drag a scrollable element (let the browser scroll it)
            if ((startEvent.target as HTMLElement).closest('.scrollable') != null) {
               startCoefficient = { l: 0, t: 0, w: 0, h: 0 }
            }
         }

         const movement =
            new THREE.Vector2(currentEvent.clientX - previousEvent.clientX, currentEvent.clientY - previousEvent.clientY)

         const sizeChange = new THREE.Vector2(startCoefficient.w, startCoefficient.h).multiply(movement)
         const limitedSizeChange = limitSizeChange(sizeChange)

         // calculate effective movement from sizeChange adjusted for styling limits
         if (startCoefficient.l != 1 || startCoefficient.t != 1) {
            movement.set(
               (startCoefficient.w == 0) ? 0 : 1 / startCoefficient.w,
            (startCoefficient.h == 0) ? 0 : 1 / startCoefficient.h
            ).multiply(limitedSizeChange)
         }

         const locationChange = new THREE.Vector2(startCoefficient.l, startCoefficient.t).multiply(movement)
         const movingElement = (startEvent.target as HTMLElement).closest('.draggable') as HTMLElement
         callback(
            locationChange.x, locationChange.y,
            limitedSizeChange.width, limitedSizeChange.height,
            isDrop, movingElement)
      }
   } else {
      recognizeDragAndDrop(element,
         (  startEvent: PointerEvent,
            previousEvent: PointerEvent,
            currentEvent: PointerEvent,
            isDrop: boolean
         ) => {
            mouseMove(startEvent, previousEvent, currentEvent, isDrop)
         })

      function mouseMove (
         startEvent: PointerEvent,
         previousEvent: PointerEvent,
         currentEvent: PointerEvent,
         isDrop: boolean
      ) {
         // Drag-and-drop over resizeHandle resizes model element; otherwise drag-and-drop moves model element
         const drag =
            new THREE.Vector2(currentEvent.clientX - previousEvent.clientX, currentEvent.clientY - previousEvent.clientY)
         const resizing = element.querySelector('.resize-handle')?.contains(startEvent.target as HTMLElement)
         if (resizing) {
            callback(0, 0, drag.x, drag.y)
         } else {
            const movingElement = (startEvent.target as HTMLElement).closest('.draggable') as HTMLElement
            callback(drag.x, drag.y, 0, 0, isDrop, movingElement)
         }
      }
   }

   // adjust sizeChange so that running into min-width/min-height styling limits doesn't move element
   function limitSizeChange (sizeChange: THREE.Vector2): THREE.Vector2 {
      let limitedSizeChange = sizeChange
      if (sizeChange.x < 0 || sizeChange.y < 0) {
         const {width, height} = element.getBoundingClientRect()
         limitedSizeChange = new THREE.Vector2().set(
            (sizeChange.x < 0) ? Math.max(minElement.width - width, sizeChange.x) : sizeChange.x,
            (sizeChange.y < 0) ? Math.max(minElement.height - height, sizeChange.y) : sizeChange.y
         )
      }
      return limitedSizeChange
   }
}
/*
```
### Utility routines
```javascript
 */
export function isLongTap (startEvent: PointerEvent, endEvent: PointerEvent): boolean {
   return startEvent.pointerType !== 'mouse'                 // long tap only used on touch device
      && (endEvent.timeStamp - startEvent.timeStamp) > CLICK_TIME
      && isTrivialMove(startEvent, endEvent)
}

function isClick (
   startEvent: PointerEvent | MouseEvent,
   endEvent: PointerEvent | MouseEvent
): boolean {
   return (endEvent.timeStamp - startEvent.timeStamp) < CLICK_TIME
      && isTrivialMove(startEvent, endEvent)
}

function isTrivialMove (
   startEvent: PointerEvent | MouseEvent,
   endEvent: PointerEvent | MouseEvent
): boolean {
   const dx = endEvent.clientX - startEvent.clientX
   const dy = endEvent.clientY - startEvent.clientY
   return Math.hypot(dx, dy) < CLICK_MOVE
}
