export declare class Group {
    #private;
    multtable: any;
    representations: any;
    names: string[];
    gapname: any;
    shortName: string;
    links: any;
    declaredGenerators: any;
    definition: any;
    phrase: string;
    notes: string;
    author: string;
    cayleyDiagrams: never[];
    symmetryObjects: never[];
    custom: {};
    library: any;
    lastModifiedOnServer: any;
    URL: any;
    constructor();
    static fromMulttable(multtable: any): Group;
    static fromGroupFileJSON(json: any): any;
    static fromLocalCopyJSON(json: any): any;
    get name(): any;
    get customName(): any;
    set customName(customName: any);
    get gapid(): string;
    set gapid(gapid: string);
    get other_names(): string[];
    get representation(): any;
    set representation(representation: any);
    get representationIndex(): any;
    set representationIndex(representationIndex: any);
    get representationIsUserDefined(): boolean;
    get userRepresentations(): any;
    deleteUserRepresentation(userIndex: any): void;
    get longestHTMLLabel(): any;
    get userNotes(): any;
    set userNotes(userNotes: any);
    get center(): any;
    get commutatorSubgroup(): any;
    get conjugacyClasses(): any;
    get conjugateSubgroupClasses(): any;
    get elementPowers(): any;
    get elementPrimePowers(): any;
    get elementOrders(): any;
    get elements(): any[];
    get generators(): any;
    get inverses(): any;
    get isAbelian(): any;
    get isCyclic(): any;
    get isSimple(): any;
    get isSolvable(): any;
    get nonAbelianExample(): any;
    get nontrivialProperNormalSubgroups(): any;
    get nontrivialProperSubgroups(): any;
    get normalSubgroups(): any;
    get order(): any;
    get orderClasses(): any;
    get orderClassSizes(): any;
    get relations(): any;
    get subgroups(): any;
    get subgroupOrders(): any;
    mult(a: any, b: any): any;
    conjugate(h: any, g: any): any;
    closure(generators: any): any;
    getElementPowerArray(element: any): number[];
    getSubgroupByElements(elements: any): any;
}
