import { BitSet } from './BitSet.js';
import type { Subgroup } from './Subgroup.js';
import type { XMLCayleyDiagram, XMLSymmetryObject } from './XMLGroup.js';
type GroupJSON = any;
export type GroupFileJSON = any;
export declare class Group {
    #private;
    multtable: groupElement[][];
    representations: html[][];
    names: html[];
    gapname?: string;
    shortName: string;
    links: Maybe<string[]>;
    declaredGenerators: Maybe<groupElement[][]>;
    definition: Maybe<html>;
    phrase: html;
    notes: string;
    author: string;
    cayleyDiagrams: XMLCayleyDiagram[];
    symmetryObjects: XMLSymmetryObject[];
    custom: {
        [key: string]: any;
    };
    library?: void | 'extended' | 'notable' | 'generated';
    lastModifiedOnServer?: Maybe<string>;
    thumbnails?: any;
    URL: string;
    _gapid_lock?: string;
    constructor(multtable: groupElement[][]);
    static fromMulttable(multtable: groupElement[][]): Group;
    static fromGroupFileJSON(json: GroupJSON): Group;
    static fromLocalCopyJSON(json: GroupFileJSON): Group;
    get name(): html;
    get customName(): html;
    set customName(customName: html);
    get gapid(): string;
    set gapid(gapid: string);
    get other_names(): string[];
    get representation(): html[];
    set representation(representation: html[]);
    get representationIndex(): number;
    set representationIndex(representationIndex: number);
    get representationIsUserDefined(): boolean;
    get userRepresentations(): html[][];
    set userRepresentations(userRepresentations: html[][]);
    deleteUserRepresentation(userIndex: number): void;
    get longestHTMLLabel(): number;
    get userNotes(): string;
    set userNotes(userNotes: string);
    get center(): Subgroup;
    get commutatorSubgroup(): Subgroup;
    get conjugacyClasses(): BitSet[];
    get conjugateSubgroupClasses(): BitSet[];
    get elementPowers(): BitSet[];
    get elementPrimePowers(): BitSet[];
    get elementOrders(): number[];
    get elements(): groupElement[];
    get generators(): groupElement[];
    get inverses(): groupElement[];
    get isAbelian(): boolean;
    get isCyclic(): boolean;
    get isSimple(): boolean;
    get isSolvable(): boolean;
    get nonAbelianExample(): Maybe<[groupElement, groupElement]>;
    get nontrivialProperNormalSubgroups(): Subgroup[];
    get nontrivialProperSubgroups(): Subgroup[];
    get normalSubgroups(): Subgroup[];
    get order(): number;
    get orderClasses(): BitSet[];
    get orderClassSizes(): number[];
    get relations(): groupElement[][];
    get subgroups(): Subgroup[];
    get subgroupOrders(): number[];
    mult(a: groupElement, b: groupElement): groupElement;
    conjugate(h: groupElement, g: groupElement): groupElement;
    closure(generators: BitSet | groupElement[]): BitSet;
    getElementPowerArray(element: groupElement): groupElement[];
    getSubgroupByElements(elements: BitSet | groupElement[]): Maybe<Subgroup>;
}
export {};
