import { BitSet } from './BitSet.js';
import { HighlightControlViewModel, DisplayItem, AbstractSubset, Subgroop, Subset } from './HighlightControlViewModel.js';
export declare class HighlightControlView {
    viewModel: HighlightControlViewModel;
    rootElement: HTMLElement;
    itemMap: Maybe<DisplayItemView>[];
    constructor(viewModel: HighlightControlViewModel, rootElement: HTMLElement);
    addElement(displayItem: DisplayItem): void;
    allConjugacyClassesHTML(): html;
    allOrderClassesHTML(): html;
    makeLongList(subsetView: DisplayItemView, htmlGenerator: (subsetView: DisplayItemView, otherSubsetView: DisplayItemView) => html): html;
    removeElement(displayItem: DisplayItem): void;
    private showHeaderMenu;
    showItemMenu(event: MouseEvent, subsetId: number): void;
    intersectionItemHTML(subsetView: DisplayItemView, otherSubsetView: DisplayItemView): html;
    unionItemHTML(subsetView: DisplayItemView, otherSubsetView: DisplayItemView): html;
    elementwiseProductItemHTML(subsetView: DisplayItemView, otherSubsetView: DisplayItemView): html;
    highlightItemHTML(itemView: DisplayItemView): html;
    updateHighlightMark(): void;
    confirmSubsetSave(matchingSubsets: (Subgroop | Subset)[], explanation: Maybe<html>, type?: 'closure' | 'normalizer' | 'union' | 'intersection' | 'elementwiseProduct' | null, subset?: Maybe<AbstractSubset>, subset2?: Maybe<AbstractSubset>): Promise<boolean>;
    nextSubsetName(): html;
    makeSubsetEditor(subsetId: Maybe<integer>): void;
    clearAll(): void;
    static highlightControlHTML: html;
}
declare class DisplayItemView {
    item: DisplayItem;
    view: HighlightControlView;
    viewModel: HighlightControlViewModel;
    htmlElement: Maybe<HTMLElement>;
    partitionViews: DisplayItemView[];
    schemeView: Maybe<DisplayItemView>;
    constructor(item: DisplayItem, view: HighlightControlView, schemeView?: Maybe<DisplayItemView>);
    get id(): number;
    get rootElement(): HTMLElement;
    get elements(): Maybe<BitSet>;
    get name(): html;
    get displayLine(): html;
    get menu(): html;
    destroy(): void;
    highlight(): void;
    get clickAction(): html;
    get contextAction(): html;
    get info(): html;
    get closureExplanation(): html;
    get normalizerExplanation(): html;
    unionExplanation(otherView: DisplayItemView): html;
    intersectionExplanation(otherView: DisplayItemView): html;
    elementwiseProductExplanation(otherView: DisplayItemView): html;
    get elementRepresentations(): html[];
    get elementString(): string;
    private buildScheme;
    private appendToSection;
    private mountPartition;
    private subgroopDisplayLine;
    private subsetDisplayLine;
    private conjugacyClassDisplayLine;
    private orderClassDisplayLine;
    private cosetDisplayLine;
    private subgroopMenu;
    private subsetMenu;
    private partitionMenu;
}
export {};
