export { getGroupLibrary, saveGroupLibrary, getSettings, saveSettings, getTableConfig, saveTableConfig, getStoredSheet, saveStoredSheet, removeStoredSheet, listStoredSheets, getPassedSheet, setPassedSheet, getPassedJSON, setPassedJSON, };
declare function getGroupLibrary(): Promise<unknown>;
declare function saveGroupLibrary(groupLibrary: unknown): Promise<unknown>;
declare function getSettings(): Promise<unknown>;
declare function saveSettings(settings: unknown): Promise<unknown>;
declare function getTableConfig(): Promise<unknown>;
declare function saveTableConfig(config: unknown): Promise<unknown>;
declare function getStoredSheet(sheetName: string): Promise<unknown>;
declare function saveStoredSheet(sheetName: string, sheet: unknown): Promise<unknown>;
declare function removeStoredSheet(sheetName: string): Promise<unknown>;
declare function listStoredSheets(): Promise<string[]>;
declare function getPassedSheet(): Promise<unknown>;
declare function setPassedSheet(passedSheet: unknown): Promise<unknown>;
declare function getPassedJSON(): Promise<unknown>;
declare function setPassedJSON(passedJSON: unknown): Promise<unknown>;
